// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ParksLookup.Models;

namespace ParksLookup.Migrations
{
    [DbContext(typeof(ParksLookupContext))]
    [Migration("20200403203528_UpdateSeedData")]
    partial class UpdateSeedData
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("ParksLookup.Models.Park", b =>
                {
                    b.Property<int>("ParkId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Agency")
                        .IsRequired()
                        .HasMaxLength(100);

                    b.Property<bool>("Campsites");

                    b.Property<string>("Description")
                        .IsRequired();

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100);

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(100);

                    b.HasKey("ParkId");

                    b.ToTable("Parks");

                    b.HasData(
                        new
                        {
                            ParkId = 1,
                            Agency = "National Park Service",
                            Campsites = true,
                            Description = "Located in southern Utah near the city of Springdale. The park provides access to varied hiking, canyoneering, and water adventures.",
                            Name = "Zion",
                            State = "Utah"
                        },
                        new
                        {
                            ParkId = 2,
                            Agency = "National Park Service",
                            Campsites = true,
                            Description = "Truly grand: a steep-sided canyon carved by the Colorado River. The Grand Canyon features layered bands of red rock revealing millions of years of geological history. Viewpoints include Mather Point, Yavapai Observation Station and architect Mary Colter’s Lookout Studio and her Desert View Watchtower.",
                            Name = "Grand Canyon",
                            State = "Arizona"
                        },
                        new
                        {
                            ParkId = 3,
                            Agency = "National Park Service",
                            Campsites = true,
                            Description = "This volcanic crater is the deepest lake in the United States and ninth-deepest lake in the world. Located in south-central Oregon, Crater Lake  is famous for its deep blue color and water clarity.",
                            Name = "Crater Lake",
                            State = "Oregon"
                        },
                        new
                        {
                            ParkId = 4,
                            Agency = "Portland Parks & Recreation Department",
                            Campsites = false,
                            Description = "1300 acres of urban forest in Portland, OR, stretching along hillsides overlooking the Willamette River. Great running/hiking trails.",
                            Name = "Forest Park",
                            State = "Oregon"
                        },
                        new
                        {
                            ParkId = 5,
                            Agency = "Maryland Department of Natural Resources (DNR)",
                            Campsites = false,
                            Description = "Public recreation area in Lusby, Calvert County, Maryland, that protects a portion of cliffs that extend for 24 miles along the eastern flank of the Calvert Peninsula on the west side of Chesapeake Bay from Chesapeake Beach southward to Drum Point. Nice boardwalk for a wooded hike to the beach.",
                            Name = "Calvert Cliffs",
                            State = "Maryland"
                        },
                        new
                        {
                            ParkId = 6,
                            Agency = "National Park Service",
                            Campsites = true,
                            Description = "Hottest, driest, and lowest national park. Death Valley is the largest U.S. National Park outside Alaska at 3.4 million acres. Nearly 1000 miles of paved and dirt roads provide access to locations both popular and remote. 91% of the park is protected as officially designated Wilderness. That wild country includes low valley floors crusted with barren salt flats, rugged mountains rising as much as 11,000 feet, deep and winding canyons, rolling sand dunes, and spring-fed oases.",
                            Name = "Death Valley",
                            State = "California"
                        },
                        new
                        {
                            ParkId = 7,
                            Agency = "Oregon State Parks",
                            Campsites = true,
                            Description = "Located in central Oregon's high desert near the communities of Redmond and Terrebonne. The park, having several thousand climbs and more than a thousand of whihch are bolted routes, is a haven for rock climbers. Miles of hiking and mountain biking trails also wind through the canyon.",
                            Name = "Smith Rock",
                            State = "Oregon"
                        },
                        new
                        {
                            ParkId = 8,
                            Agency = "Oregon State Parks",
                            Campsites = true,
                            Description = "Formerly the primary military defense  installation in the three-fort, Harbor Defense System at the mouth of the Columbia River. Now, Fort Stevens is a 4,300-acre park offering a variety of recreational opportunities, including camping, beach-combing, freshwater lake swimming, hiking trails, wildlife viewing and a historic shipwreck.",
                            Name = "Fort Stevens State Park",
                            State = "Oregon"
                        },
                        new
                        {
                            ParkId = 9,
                            Agency = "National Park Service",
                            Campsites = false,
                            Description = "Part of the John Day Fossil Beds. The painted hills are located about 9 miles northwest of Mitchell, Oregon and distinguished by their stripes of red, tan, orange, and black. If you visit, stay off the dirt to help preserve the monument!",
                            Name = "Painted Hills",
                            State = "Oregon"
                        },
                        new
                        {
                            ParkId = 10,
                            Agency = "Washington State Parks",
                            Campsites = true,
                            Description = "Public recreation area on Orcas Island in Puget Sound's San Juan Islands. This 5,424-acre park offers abundant camping (151 sites), five freshwater lakes for swimming and non-motorized boating, and more than 30 miles of hiking, bicycling, mountain biking and equestrian trails.",
                            Name = "Moran State Park",
                            State = "Washington"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
